src/App.vue
src/components/CounterSection.vue
src/components/MachineLearningSection.vue

Redmine: https://dev.sun-asterisk.com/issues/443229

Add stats (counter) section

---

src/App.vue
src/components/CounterSection.vue
src/components/TopSection.vue

Redmine: https://dev.sun-asterisk.com/issues/444642

Add top users, articles, tags section

---

src/components/CounterSection.vue

Remove chart bar of counter section if screen is mobile

---

package.json
src/components/FirstSection.vue
src/components/Footer.vue
src/components/MachineLearningSection.vue
yarn.lock

- Make footer similar to Viblo
- Other small modifications...

Make footer similar to Viblo

---

package.json
src/components/CounterSection.vue
yarn.lock

Add thousand separate format for numbers

---

package.json
src/App.vue
src/components/CounterSection.vue
vue.config.js
yarn.lock

Add prerender
Remove `numbro` package (use `toLocaleString()` method instead).
Use normal import

feat: add prerender, some small optimization

---

src/components/TopSection.vue

refactor: 2 columns for top section

---

package.json
src/App.vue
src/components/CounterSection.vue
src/components/NumberCount.vue
src/components/SectionMilestone.vue
src/components/TopSection.vue
yarn.lock

feat: add some animation

---

src/components/CounterSection.vue
src/components/NumberCount.vue
src/includes/event-bus.js

https://dev.sun-asterisk.com/issues/451416?issue_count=8&issue_position=4&next_issue_id=451413&prev_issue_id=451419

fix: reduced aniamtion and display chart fit height on page Stats

---

src/App.vue
src/components/FirstSection.vue
src/components/MachineLearningSection.vue

Header section always has min-height is 100vh, both mobile and large
screen
Fix ML section background

fix: header fits screen, ml section background fix

---

src/components/SectionAbout.vue

https://dev.sun-asterisk.com/issues/451419

feat: add animation for the SectionAbout

---

src/App.vue
src/components/CounterSection.vue

Task: https://dev.sun-asterisk.com/issues/451425

fix: horizontal scroll

---

src/components/FirstSection.vue
src/components/SectionAbout.vue

fix: fit screen page sectionAbout

---

src/components/TopSection.vue

style: hexagon section left to right order on mobile

---

src/App.vue
src/components/MachineLearningSection.vue
src/components/Menu.vue
src/components/TopSection.vue
vue.config.js

Change prerender to use JSDom renderer (instead of puppeteer renderer)
Only show "scroll to top" button if not on top
Indentation fix
Some other style fixes

refactor: change prerender to use jsdom

---

src/components/CounterSection.vue

Task: https://dev.sun-asterisk.com/issues/472346

feat: add get dynamic data

---

yarn.lock

chore(deps): no vulnerabilities in the dependencies #53

---

src/data/counter-items.js

Increase pageview from 1.900.000 to 2.000.000

chore: update pageview

---

src/components/SectionService.vue
src/components/switchLanguage.vue
src/data/milestone-items.js
src/main.js
src/store/index.js

https://user-images.githubusercontent.com/100565829/163908950-92650d45-b805-4d93-8507-44c65a2a36f1.mp4
https://user-images.githubusercontent.com/100565829/163909100-1d1660eb-96ba-42a2-9384-e5fac89d4ba7.mp4

chore: add multiple language

---

src/data/services.js

chore: fix link viblo partner
